/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.titansinc.stickynotesapp;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedWriter;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.OutputStreamWriter;
import java.io.Serializable;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JPanel;

/**
 *
 * @author zubair
 */
public class NotePad extends JPanel {

    /**
     * Creates new form NotePad
     */
    JFrame frame;
    int pX,pY,ID;
    String Text="";
    StickyPaper stickypaper;
    StickyNotes TopClass;
    //BufferedWriter output;
   DataOutputStream output;
    static String URL= "/var/tmp/.StickyNotes/";
    File file;
    
    public NotePad(StickyNotes TopClass) {
        this.TopClass=TopClass;
        TopClass.count++;
        this.ID=TopClass.ID;
        TopClass.Notes.put(TopClass.ID++, this);
        initComponents();
        CreateNewPaper();
        CreateNewFrame();
        CreateNewSessionFile();
    }
    
    public NotePad(StickyNotes TopClass, int ID, String Text){
        this.TopClass=TopClass;     
        this.ID=ID;
        TopClass.Notes.put(ID, this);
        this.Text=Text;
        initComponents();
        CreateNewPaper();
        CreateNewFrame();
        CreateNewSessionFile();
        stickypaper.drawAgain(this.Text);                
    }
    
    private void CreateNewSessionFile(){
         try{
             file=new File(URL+ID+".sz");
            
             if(!file.exists())
                file.createNewFile();
             file.deleteOnExit();
             
        }catch(Exception e){System.out.println("File Not found exception "); e.printStackTrace();}
    }
    
    
    private void CreateNewPaper(){
        stickypaper=new StickyPaper();
        Paper.setLayout(new BorderLayout());
        Paper.add(stickypaper);
        Paper.revalidate();
      
    }
    
    
    
    private JFrame CreateNewFrame(){
        
        frame=new JFrame();
        frame.setUndecorated(true);
        //Use Screen size as bound to random numbers
        frame.setLocation(new Random().nextInt(2000),new Random().nextInt(900));
        frame.add(this);
        frame.pack();
        try{
        frame.setOpacity((float) 0.85);
        }catch(Exception e){}
        frame.setVisible(true);
        frame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
               FrameKeyTyped(evt);
            }
        });
        frame.setResizable(false);
        frame.validate();
        return frame;
        
    }    
    
    private void FrameKeyTyped(java.awt.event.KeyEvent evt) {                               
    
        
        if(evt.getKeyChar()=='\b'){
            if(Text.length()!=0)
                Text=Text.substring(0, Text.length()-1);
        }
        else if(evt.getKeyChar()==java.awt.event.KeyEvent.VK_ENTER){
            Text=Text+" \n ";
        }
        else{
            Text=Text+evt.getKeyChar();            
        }
       
        stickypaper.drawAgain(Text);
        SaveSession();
        
    }   
    
    
    private void SaveSession() {
        try {
            output=new DataOutputStream(new FileOutputStream(file,false));
            output.write(Text.getBytes());
            output.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Paper = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        CloseBut = new javax.swing.JLabel();
        NewNoteBut = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 224, 107));

        Paper.setBackground(new java.awt.Color(254, 224, 107));
        Paper.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PaperjPanel1MouseDragged(evt);
            }
        });
        Paper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PaperjPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout PaperLayout = new javax.swing.GroupLayout(Paper);
        Paper.setLayout(PaperLayout);
        PaperLayout.setHorizontalGroup(
            PaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        PaperLayout.setVerticalGroup(
            PaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        Header.setBackground(new java.awt.Color(173, 87, 1));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        CloseBut.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/com/titansinc/stickynotesapp/close.png")).getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH)));
        CloseBut.setText("X");
        CloseBut.setText("");
        CloseBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseButMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseButMouseEntered(evt);
            }
        });

        NewNoteBut.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/com/titansinc/stickynotesapp/newnote.png")).getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH)));
        NewNoteBut.setText("X");
        NewNoteBut.setText("");
        NewNoteBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewNoteButMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewNoteButMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewNoteButMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addComponent(NewNoteBut, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseBut, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CloseBut, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
            .addComponent(NewNoteBut, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Paper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Paper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PaperjPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaperjPanel1MouseDragged
        // TODO add your handling code here:
        frame.setLocation(frame.getLocation().x+evt.getX()-pX,frame.getLocation().y+evt.getY()-pY);
 
    }//GEN-LAST:event_PaperjPanel1MouseDragged

    private void PaperjPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaperjPanel1MousePressed
        // TODO add your handling code here:
        pX=evt.getX();
        pY=evt.getY();
    }//GEN-LAST:event_PaperjPanel1MousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // TODO add your handling code here:
        frame.setLocation(frame.getLocation().x+evt.getX()-pX,frame.getLocation().y+evt.getY()-pY);
       
    }//GEN-LAST:event_HeaderMouseDragged
    
    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        // TODO add your handling code here:
        pX=evt.getX();
        pY=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void CloseButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButMouseEntered
        // TODO add your handling code here:
        CloseBut.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/com/titansinc/stickynotesapp/close_zoom.png")).getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH)));
       
    }//GEN-LAST:event_CloseButMouseEntered

    private void CloseButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButMouseExited
        // TODO add your handling code here:
        CloseBut.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/com/titansinc/stickynotesapp/close.png")).getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_CloseButMouseExited

    private void CloseButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButMouseClicked
        // TODO add your handling code here:
        frame.setVisible(false);
        TopClass.count--;
        TopClass.Notes.remove(Integer.valueOf(ID));
        file.delete();
        System.out.println(TopClass.count);
        if(TopClass.count<=0){            
            System.exit(0);
                    System.out.println("I am here ");

        }
    }//GEN-LAST:event_CloseButMouseClicked

    private void NewNoteButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewNoteButMouseClicked
        // TODO add your handling code here:
        new NotePad(TopClass);
    }//GEN-LAST:event_NewNoteButMouseClicked

    private void NewNoteButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewNoteButMouseExited
        // TODO add your handling code here:
        NewNoteBut.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/com/titansinc/stickynotesapp/newnote.png")).getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_NewNoteButMouseExited

    private void NewNoteButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewNoteButMouseEntered
        // TODO add your handling code here:
        NewNoteBut.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/com/titansinc/stickynotesapp/newnote_zoom.png")).getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_NewNoteButMouseEntered
 
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseBut;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel NewNoteBut;
    private javax.swing.JPanel Paper;
    // End of variables declaration//GEN-END:variables
}
